
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      -
        name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: pytest-junit
          path: 'pytest.xml'
          reporter: java-junit
          
      -
        name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: "eslint-junit"
          path: 'eslint-junit.xml'
          reporter: java-junit
          
      -
        name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: "jest-junit as java-junit"
          path: 'jest-junit.xml'
          reporter: java-junit

      -
        name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: "jest-junit"
          path: 'jest-junit.xml'
          reporter: jest-junit
